[theme]
mode = "dark"
source = "custom"
custom_palette = "Tokyo-Night"

[bar.default]
position = "top"
thickness = 34
background_opacity = 0.93
radius = 12
padding = 14
widget_spacing = 6
margin_ends = 4
margin_edge = 4
reserve_space = true
capsule = true
capsule_fill = "surface_variant"
capsule_thickness = 0.76
capsule_opacity = 1.0
start = ["launcher", "workspaces", "sysmon", "active_window", "media"]
center = ["clock"]
end = [
  "privacy",
  "screenshot",
  "tray",
  "notifications",
  "battery",
  "volume",
  "brightness",
  "keyboard_layout",
  "control-center",
]

[bar.workday]
enabled = false
position = "right"
thickness = 64
margin_ends = 52
margin_edge = 4
padding = 0
radius = 12
reserve_space = true
capsule = false
start = []
center = ["cian-h/workday-progress:progress"]
end = []

[bar.workday.monitor."HP Inc. HP E23 G4 CN41330H6Q"]
enabled = true

[widget.launcher]
glyph = "rocket"

[widget.clock]
format = "{:%H:%M %a, %b %d}"
vertical_format = "{:%H %M - %d %m}"
tooltip_format = "{:%H:%M %a, %b %d}"

[widget.media]
artist_first = true
hide_when_no_media = true

[widget.volume]
actions = { middle = "exec pwvucontrol || pavucontrol" }

[widget.control-center]
glyph = "noctalia"

[dock]
enabled = true
position = "bottom"
auto_hide = true
smart_auto_hide = false
magnification = true
magnification_scale = 1.30
icon_size = 40
main_axis_padding = 5
cross_axis_padding = 5
item_spacing = 4
background_opacity = 0.90
radius = 12
border_width = 1.0
shadow = true
show_running = true
pinned = ["firefox", "kitty"]

[control_center]
sidebar = "compact"
width = 700

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "audio"

[[control_center.shortcuts]]
type = "dark_mode"

[audio]
enable_overdrive = true

[brightness]
enable_ddcutil = true
minimum_brightness = 0.05

[wallpaper]
enabled = true
directory = "/home/cianh/Pictures/Wallpapers"
fill_mode = "crop"
transition_duration = 1500
edge_smoothness = 0.05

[wallpaper.default]
path = "/home/cianh/Pictures/Wallpapers/wallhaven-l88xey.png"

[wallpaper.automation]
enabled = true
interval_seconds = 300
order = "random"

[idle]
behavior_order = ["lock", "screen-off", "suspend"]
pre_action_fade_seconds = 5.0

[idle.behavior.lock]
timeout = 600
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 660
action = "screen_off"
enabled = true

[idle.behavior.suspend]
timeout = 1800
action = "lock_and_suspend"
enabled = true

[notification]
position = "top_right"
layer = "overlay"
history_retention_hours = 1

[osd]
position = "top_right"
orientation = "horizontal"

[shell]
avatar_path = "/home/cianh/Pictures/face.png"
lang = "en-GB"
telemetry_enabled = false
polkit_agent = true

[lockscreen]
lock_before_suspend = true

[shell.panel]
polkit_placement = "floating"
polkit_position = "center"

[plugins]
enabled = [
  "noctalia/screen_recorder",
  "kenn/keybind-cheatsheet",
  "cian-h/workday-progress",
]
auto_update = "all"

[[plugins.source]]
name = "official"
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
enabled = true

[[plugins.source]]
name = "community"
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
enabled = true

[[plugins.source]]
name = "my-plugins"
kind = "git"
location = "https://github.com/Cian-H/noctalia-plugins"
enabled = true
