exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = systemctl --user start graphical-session.target

exec-once = noctalia

# Some default env vars.
env = XDG_CURRENT_DESKTOP,Hyprland
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = HYPRCURSOR_THEME,"phinger-cursor"
env = HYPRCURSOR_SIZE,28

$mainMod = SUPER
$mainModShift = SUPER_SHIFT

$menu = walker
$terminal = ghostty +new-window
$browser = vivaldi
$noteManager = obsidian
$noteManagerSearch = walker-obsidian-search
$literatureManager = zotero
$localDocs = zeal
$musicPlayer = sone
$bluetoothManager = noctalia msg panel-toggle control-center bluetooth
$officeSuite = onlyoffice-desktopeditors
$fileManager = thunar
$perfMonitor = missioncenter
$terminalBackup = kitty
$screenshot = hyprshot --mode region -o ~/Pictures/Screenshot/
$lockscreen = noctalia msg session lock
$powerMenu = noctalia msg panel-toggle session
$colorpicker = hyprpicker -a
$emojipicker = walker -m symbols
$cheatsheet = noctalia msg panel-toggle kenn/keybind-cheatsheet:cheatsheet

source = monitors.conf
source = variables.conf
source = binds.conf
source = inputs.conf
source = appearance.conf
