source ../nu_scripts/custom-completions/auto-generate/completions/7z.nu
source ../nu_scripts/custom-completions/auto-generate/completions/adduser.nu
source ../nu_scripts/custom-completions/auto-generate/completions/apk.nu
source ../nu_scripts/custom-completions/auto-generate/completions/apk.nu
source ../nu_scripts/custom-completions/auto-generate/completions/apt-get.nu
source ../nu_scripts/custom-completions/auto-generate/completions/aptitude.nu
source ../nu_scripts/custom-completions/auto-generate/completions/base64.nu
source ../nu_scripts/custom-completions/auto-generate/completions/btrfs.nu
source ../nu_scripts/custom-completions/auto-generate/completions/conda.nu
source ../nu_scripts/custom-completions/auto-generate/completions/conjure.nu
source ../nu_scripts/custom-completions/auto-generate/completions/convert.nu
source ../nu_scripts/custom-completions/auto-generate/completions/dconf.nu
source ../nu_scripts/custom-completions/auto-generate/completions/dd.nu
source ../nu_scripts/custom-completions/auto-generate/completions/diff.nu
source ../nu_scripts/custom-completions/auto-generate/completions/dmesg.nu
source ../nu_scripts/custom-completions/auto-generate/completions/dnf.nu
source ../nu_scripts/custom-completions/auto-generate/completions/feh.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ffmpeg.nu
source ../nu_scripts/custom-completions/auto-generate/completions/flatpak.nu
source ../nu_scripts/custom-completions/auto-generate/completions/fzf.nu
source ../nu_scripts/custom-completions/auto-generate/completions/gcc.nu
source ../nu_scripts/custom-completions/auto-generate/completions/gdb.nu
source ../nu_scripts/custom-completions/auto-generate/completions/go.nu
source ../nu_scripts/custom-completions/auto-generate/completions/grep.nu
source ../nu_scripts/custom-completions/auto-generate/completions/gunzip.nu
source ../nu_scripts/custom-completions/auto-generate/completions/hugo.nu
source ../nu_scripts/custom-completions/auto-generate/completions/iex.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ip.nu
source ../nu_scripts/custom-completions/auto-generate/completions/journalctl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/jq.nu
source ../nu_scripts/custom-completions/auto-generate/completions/julia.nu
source ../nu_scripts/custom-completions/auto-generate/completions/kill.nu
source ../nu_scripts/custom-completions/auto-generate/completions/killall.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ln.nu
source ../nu_scripts/custom-completions/auto-generate/completions/localectl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/lsblk.nu
source ../nu_scripts/custom-completions/auto-generate/completions/lua.nu
source ../nu_scripts/custom-completions/auto-generate/completions/lz4.nu
source ../nu_scripts/custom-completions/auto-generate/completions/make.nu
source ../nu_scripts/custom-completions/auto-generate/completions/makepkg.nu
source ../nu_scripts/custom-completions/auto-generate/completions/md5sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/micro.nu
source ../nu_scripts/custom-completions/auto-generate/completions/minikube.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mkdocs.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mkfs.fat.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mkfs.vfat.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mkinitcpio.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mkpasswd.nu
source ../nu_scripts/custom-completions/auto-generate/completions/modinfo.nu
source ../nu_scripts/custom-completions/auto-generate/completions/modprobe.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mosh.nu
source ../nu_scripts/custom-completions/auto-generate/completions/mount.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ncat.nu
source ../nu_scripts/custom-completions/auto-generate/completions/networkctl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/nl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/nm.nu
source ../nu_scripts/custom-completions/auto-generate/completions/nmap.nu
source ../nu_scripts/custom-completions/auto-generate/completions/nmcli.nu
source ../nu_scripts/custom-completions/auto-generate/completions/npkg.nu
source ../nu_scripts/custom-completions/auto-generate/completions/nvim.nu
source ../nu_scripts/custom-completions/auto-generate/completions/objdump.nu
source ../nu_scripts/custom-completions/auto-generate/completions/optimus-manager.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pacaur.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pacman-color.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pacman-key.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pacman.nu
source ../nu_scripts/custom-completions/auto-generate/completions/patch.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pgrep.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ping.nu
source ../nu_scripts/custom-completions/auto-generate/completions/pinky.nu
source ../nu_scripts/custom-completions/auto-generate/completions/poweroff.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ps.nu
source ../nu_scripts/custom-completions/auto-generate/completions/python.nu
source ../nu_scripts/custom-completions/auto-generate/completions/python3.nu
source ../nu_scripts/custom-completions/auto-generate/completions/readlink.nu
source ../nu_scripts/custom-completions/auto-generate/completions/realpath.nu
source ../nu_scripts/custom-completions/auto-generate/completions/resolvectl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/rfkill.nu
source ../nu_scripts/custom-completions/auto-generate/completions/rmdir.nu
source ../nu_scripts/custom-completions/auto-generate/completions/rmmod.nu
source ../nu_scripts/custom-completions/auto-generate/completions/rsync.nu
source ../nu_scripts/custom-completions/auto-generate/completions/rustc.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sbcl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/scp.nu
source ../nu_scripts/custom-completions/auto-generate/completions/setfacl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/setsid.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sftp.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sha1sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sha224sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sha256sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sha384sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sha512sum.nu
source ../nu_scripts/custom-completions/auto-generate/completions/ssh.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sshfs.nu
source ../nu_scripts/custom-completions/auto-generate/completions/strace.nu
source ../nu_scripts/custom-completions/auto-generate/completions/stream.nu
source ../nu_scripts/custom-completions/auto-generate/completions/su.nu
source ../nu_scripts/custom-completions/auto-generate/completions/sudo.nu
source ../nu_scripts/custom-completions/auto-generate/completions/systemctl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/test.nu
source ../nu_scripts/custom-completions/auto-generate/completions/time.nu
source ../nu_scripts/custom-completions/auto-generate/completions/timedatectl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/timeout.nu
source ../nu_scripts/custom-completions/auto-generate/completions/top.nu
source ../nu_scripts/custom-completions/auto-generate/completions/tracepath.nu
source ../nu_scripts/custom-completions/auto-generate/completions/traceroute.nu
source ../nu_scripts/custom-completions/auto-generate/completions/udevadm.nu
source ../nu_scripts/custom-completions/auto-generate/completions/umount.nu
source ../nu_scripts/custom-completions/auto-generate/completions/unexpand.nu
source ../nu_scripts/custom-completions/auto-generate/completions/unlz4.nu
source ../nu_scripts/custom-completions/auto-generate/completions/unzip.nu
source ../nu_scripts/custom-completions/auto-generate/completions/unzstd.nu
source ../nu_scripts/custom-completions/auto-generate/completions/useradd.nu
source ../nu_scripts/custom-completions/auto-generate/completions/userdbctl.nu
source ../nu_scripts/custom-completions/auto-generate/completions/usermod.nu
source ../nu_scripts/custom-completions/auto-generate/completions/w.nu
source ../nu_scripts/custom-completions/auto-generate/completions/wget.nu
source ../nu_scripts/custom-completions/auto-generate/completions/whatis.nu
source ../nu_scripts/custom-completions/auto-generate/completions/who.nu
source ../nu_scripts/custom-completions/auto-generate/completions/wine.nu
source ../nu_scripts/custom-completions/auto-generate/completions/xargs.nu
source ../nu_scripts/custom-completions/auto-generate/completions/xdg-mime.nu
source ../nu_scripts/custom-completions/auto-generate/completions/xinput.nu
source ../nu_scripts/custom-completions/auto-generate/completions/xz.nu
source ../nu_scripts/custom-completions/auto-generate/completions/zip.nu
source ../nu_scripts/custom-completions/auto-generate/completions/zstd.nu
source ../nu_scripts/custom-completions/auto-generate/completions/zypper.nu
source ../nu_scripts/custom-completions/bat/bat-completions.nu
source ../nu_scripts/custom-completions/btm/btm-completions.nu
source ../nu_scripts/custom-completions/cargo/cargo-completions.nu
source ../nu_scripts/custom-completions/curl/curl-completions.nu
source ../nu_scripts/custom-completions/docker/docker-completions.nu
source ../nu_scripts/custom-completions/flutter/flutter-completions.nu
source ../nu_scripts/custom-completions/gh/gh-completions.nu
source ../nu_scripts/custom-completions/git/git-completions.nu
source ../nu_scripts/custom-completions/glow/glow-completions.nu
source ../nu_scripts/custom-completions/jj/jj-completions.nu
source ../nu_scripts/custom-completions/just/just-completions.nu
source ../nu_scripts/custom-completions/man/man-completions.nu
source ../nu_scripts/custom-completions/mix/mix-completions.nu
source ../nu_scripts/custom-completions/mvn/mvn-completions.nu
source ../nu_scripts/custom-completions/nano/nano-completions.nu
source ../nu_scripts/custom-completions/nano/nano.nu
source ../nu_scripts/custom-completions/nix/nix-completions.nu
source ../nu_scripts/custom-completions/podman/podman-completions.nu
source ../nu_scripts/custom-completions/poetry/poetry-completions.nu
source ../nu_scripts/custom-completions/pre-commit/pre-commit-completions.nu
source ../nu_scripts/custom-completions/pytest/pytest-completions.nu
source ../nu_scripts/custom-completions/pytest/pytest-completions.nu
source ../nu_scripts/custom-completions/rg/rg-completions.nu
source ../nu_scripts/custom-completions/rustup/rustup-completions.nu
source ../nu_scripts/custom-completions/scoop/scoop-completions.nu
source ../nu_scripts/custom-completions/ssh/ssh-completions.nu
source ../nu_scripts/custom-completions/tar/tar-completions.nu
source ../nu_scripts/custom-completions/tealdeer/tldr-completions.nu
source ../nu_scripts/custom-completions/uv/uv-completions.nu
source ../nu_scripts/custom-completions/vscode/vscode-completions.nu
source ../nu_scripts/custom-completions/winget/winget-completions.nu
source ../nu_scripts/custom-completions/zellij/zellij-completions.nu
source ../nu_scripts/custom-completions/zoxide/zoxide-completions.nu
