# Inserts a blank line between shell prompts
add_newline = true
continuation_prompt = "[:::](yellow)"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 2_000  # Show command duration over 2 sec
format = " took [$duration]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold dimmed blue"
disabled = false

[username]
format = "[$user]($style)@"
style_user = "bold blue"
show_always = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true